#!/usr/bin/python

import getopt
import sys
import urllib

# Import the nagios bits for python
sys.path.insert(0, '/usr/nagios/libexec')
import utils


def usage():
    print 'Usage:'
    print '\tcheck_graphite_data <options>'
    print 'Options:'
    print '\t-c <num> | --crit=<num>\t\tCritical threshold'
    print '\t-w <num> | --warn=<num>\t\tWarning threshold'
    print '\t-u <url> | --url=<url>\t\tGraphite rawData URL'
    print '\t-r\t\t\t\tReverse - Alert when the value is UNDER warn/crit instead of OVER'
    print '\t--d1 <url> --d2 <url>\t\tDiff the latest values between two graphs'
    print '\t-s <secs> --seconds=<secs>\tAverage over the last N seconds of data'


def get_value(url, seconds=0):
    """Get the value from a Graphite graph"""

    # Make sure the url ends with '&rawData'
    if not url.endswith('&rawData'):
        url = url + '&rawData'

    data = urllib.urlopen(url).read()
    sample_period = int(data.split('|')[0].split(',')[-1])
    all_data_points = data.split('|')[-1].split(',')

    # Evaluate what graphite returned, should either be a float, or None
    # First, if the number of seconds of data we want to examine is smaller or
    # equals the graphite sample period, just grab the latest data point.
    # If that data point is None, grab the one before it.
    # If that is None too, return 0.0.
    if seconds <= sample_period:
        if eval(all_data_points[-1]):
            data_value = float(all_data_points[-1])
        elif eval(all_data_points[-2]):
            data_value = float(all_data_points[-2])
        else:
            data_value = 0.0
    else:
    # Second, if we requested more than on graphite sample period, work out how
    # many sample periods we wanted (python always rounds division *down*)
        data_points = (seconds/sample_period)
        data_set = [ float(x) for x in all_data_points[-data_points:]
                     if eval(x) ]
        if data_set:
            data_value = float( sum(data_set) / len(data_set) )
        else:
            data_value = 0.0
    return data_value


def main(argv):
    try:
        opts, args = getopt.getopt(argv, 'hru:c:w:s:', ['help', 'url=', 'crit=', 'warn=', 'seconds=', 'd1=', 'd2='])
    except getopt.GetoptError, err:
        print str(err)
        sys.exit(utils.STATE_UNKNOWN)

    url = None
    warn = None
    crit = None
    seconds = 0
    reverse = False
    diff1 = None
    diff2 = None
    for opt, arg in opts:
        if opt in ('-h', '--help'):
            usage()
            sys.exit()
        elif opt in ('-u', '--url'):
            url = arg
        elif opt in ('-w', '--warn'):
            warn = float(arg)
        elif opt in ('-c', '--crit'):
            crit = float(arg)
        elif opt in ('-s', '--seconds'):
            seconds = int(arg)
        elif opt in ('-r'):
            reverse = True
        elif opt in ('--d1'):
            diff1 = arg
        elif opt in ('--d2'):
            diff2 = arg
    if (url == None and (diff1 == None and diff2 == None)) or (warn == None) or (crit == None):
        usage()
        sys.exit(utils.STATE_UNKNOWN)
    if (diff1 == None and diff2 != None) or (diff1 != None and diff2 == None):
        usage()
        sys.exit(utils.STATE_UNKNOWN)

    if diff1 or diff2:
        graphite_data1 = get_value(diff1, seconds)
        graphite_data2 = get_value(diff2, seconds)
        graphite_data = abs(graphite_data1 - graphite_data2)
    else:
        graphite_data = get_value(url, seconds)

    print 'Current value: %s, warn threshold: %s, crit threshold: %s' % \
            (graphite_data, warn, crit)

    if reverse == True:
        if crit >= graphite_data:
            sys.exit(utils.STATE_CRITICAL)
        elif warn >= graphite_data:
            sys.exit(utils.STATE_WARNING)
        else:
            sys.exit(utils.STATE_OK)
    else:
		if crit == 0.0 and graphite_data != crit:
			print "boo!"
			sys.exit(utils.STATE_CRITICAL)
		elif graphite_data >= crit:
			sys.exit(utils.STATE_CRITICAL)
		elif warn == 0.0 and graphite_data != warn:
			sys.exit(utils.STATE_WARNING)
		elif graphite_data >= warn:
			sys.exit(utils.STATE_WARNING)
		else:
			sys.exit(utils.STATE_OK)


if __name__ == '__main__':
    main(sys.argv[1:])
